### ISSUE TITLE
Replicate current Telegram bot code for Viber bot

### ISSUE THREAD

**Issue by theanurin** [blockchain-sonar/reminder#1]
# Replicate current Telegram bot code for Viber bot

We need to replicate current Telegram's command `/reminders` for Viber

## References

* TBD Add Viber Bot API link

**Comment by olehchenusha** [comment]
API - https://developers.viber.com/docs/api/python-bot-api/ 
Habr - https://habr.com/ru/sandbox/152092/
Github - https://github.com/Viber/viber-bot-python/blob/master/sample_bot.py
